### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by meyerbro** [c29r3/solana-snapshot-finder#1]
Hey, first I would like to thank you for this great work!

I was wondering if it could make sense to add an improvement on your scripts.

I managed to build a very silly script in bash that was pinging all RPCs nodes and the ordering them by latency so that I would try downloading first from them.

It's slow (I know), it takes around 2min but once it starts downloading it pays the wait since some nodes offer me 10gbps links so that I download it much faster...

I was wondering if you could add this improvement based on this script:

```
#!/bin/bash

RPC_LIST=$(solana gossip --output json | jq -r '.[] | select(.rpcHost != null).rpcHost')
LATENCY=100
PING_TIMEOUT=$(awk -v var1=$LATENCY -v var2=1000 'BEGIN { print  ( var1 / var2 ) }')

LIST=""
for RPC in $RPC_LIST;
do
	curl -f -s -m1 -I $RPC/health > /dev/null || continue

	RPC_IP=$(echo $RPC | cut -d":" -f1)
	PING=$(ping -c1 -W$PING_TIMEOUT $RPC_IP | tail -1| awk '{print $4}' | cut -d '/' -f 2 | cut -d"." -f1)
	test $PING || continue

	if [[ "$PING" -le $LATENCY ]] ; then
		LIST+=$(echo "$RPC $PING\n")
	fi
done

GOOD_RPCS=$(echo -e $LIST | head -c -1)

echo -e "GOOD_RPCS:\n$GOOD_RPCS"

ORDERED_RPCS=$(echo -e "$GOOD_RPCS" | sort -n -k2 | head -n 10)
echo -e "\nORDERED_RPCS:\n$ORDERED_RPCS"

echo -e "SCRIPT:\n#!/bin/bash\n"
echo "SNAPSHOTS_FOLDER=/mnt/snapshots"
echo -e "cd \$SNAPSHOTS_FOLDER\n"

#for RPC in $(echo $ORDERED_RPCS);
while IFS= read -r RPC
do
	GOOD_RPC=$(echo $RPC | cut -d" " -f1)
	LATENCY=$(echo $RPC | cut -d" " -f2)
	echo -e "# $LATENCY ms\nwget --trust-server-names http://$GOOD_RPC/snapshot.tar.bz2 && exit 0\n"
done <<< $(echo -e "$ORDERED_RPCS")

echo -e "exit 1"
```

**Comment by meyerbro** [comment]
The script above will build a download script that contains the "best" (closest ones) RPCs to download a snapshot from.

**Comment by c29r3** [comment]
> Hey, first I would like to thank you for this great work!
> 
> I was wondering if it could make sense to add an improvement on your scripts.
> 
> I managed to build a very silly script in bash that was pinging all RPCs nodes and the ordering them by latency so that I would try downloading first from them.
> 
> It's slow (I know), it takes around 2min but once it starts downloading it pays the wait since some nodes offer me 10gbps links so that I download it much faster...
> 
> I was wondering if you could add this improvement based on this script:
> 
> ```
> #!/bin/bash
> 
> RPC_LIST=$(solana gossip --output json | jq -r '.[] | select(.rpcHost != null).rpcHost')
> LATENCY=100
> PING_TIMEOUT=$(awk -v var1=$LATENCY -v var2=1000 'BEGIN { print  ( var1 / var2 ) }')
> 
> LIST=""
> for RPC in $RPC_LIST;
> do
> 	curl -f -s -m1 -I $RPC/health > /dev/null || continue
> 
> 	RPC_IP=$(echo $RPC | cut -d":" -f1)
> 	PING=$(ping -c1 -W$PING_TIMEOUT $RPC_IP | tail -1| awk '{print $4}' | cut -d '/' -f 2 | cut -d"." -f1)
> 	test $PING || continue
> 
> 	if [[ "$PING" -le $LATENCY ]] ; then
> 		LIST+=$(echo "$RPC $PING\n")
> 	fi
> done
> 
> GOOD_RPCS=$(echo -e $LIST | head -c -1)
> 
> echo -e "GOOD_RPCS:\n$GOOD_RPCS"
> 
> ORDERED_RPCS=$(echo -e "$GOOD_RPCS" | sort -n -k2 | head -n 10)
> echo -e "\nORDERED_RPCS:\n$ORDERED_RPCS"
> 
> echo -e "SCRIPT:\n#!/bin/bash\n"
> echo "SNAPSHOTS_FOLDER=/mnt/snapshots"
> echo -e "cd \$SNAPSHOTS_FOLDER\n"
> 
> #for RPC in $(echo $ORDERED_RPCS);
> while IFS= read -r RPC
> do
> 	GOOD_RPC=$(echo $RPC | cut -d" " -f1)
> 	LATENCY=$(echo $RPC | cut -d" " -f2)
> 	echo -e "# $LATENCY ms\nwget --trust-server-names http://$GOOD_RPC/snapshot.tar.bz2 && exit 0\n"
> done <<< $(echo -e "$ORDERED_RPCS")
> 
> echo -e "exit 1"
> ```

Hey!
I don't understand what's the point in finding the nodes closest to you?  

My script looks for the most recent snapshot and then tests the speed of the node where the most current snapshot is found. You can specify the speed you want and the script will iterate over all nodes until the speed matches the one you specified  

`--min_download_speed 40` in megabytes
By default this parameter == 15 MB  
https://github.com/c29r3/solana-snapshot-finder/blob/main/snapshot-finder.py#L23

**Comment by meyerbro** [comment]
Hey, on my tests I found that the fastest servers were almost always in the same DC or close to you...

Another suggestion would be to keep a cache or list of good servers we could download a snapshot and try to use it maybe also keeping in account the average speed of download? This way, these could be the first nodes to check?

Have a nice week!

**Comment by c29r3** [comment]
I see that in its current form the snapshot download script is incompetent. Some more complex system like torrents already suggests itself.
