### ISSUE TITLE
Is it possible to specify where a snapshot is downloaded from?

### ISSUE THREAD

**Issue by n43o** [c29r3/solana-snapshot-finder#21]
Hello @c29r3! Thanks for this awesome tool. I was wondering if this is possible: Is it possible to pull down a snapshot from a specific node (another node I run in my network), to help speed things up by pulling it from a local source?

Thanks!

**Comment by c29r3** [comment]
> Hello @c29r3! Thanks for this awesome tool. I was wondering if this is possible: Is it possible to pull down a snapshot from a specific node (another node I run in my network), to help speed things up by pulling it from a local source?
> 
> Thanks!

Hello,
I’m glad that someone found it useful. What you are asking about can be implemented in the script, but I don’t see much sense in it, as you can directly download the snapshot from another one of your nodes using just a single command
```bash
wget  --trust-server-names http://{NODE_IP}:8899/genesis.tar.bz2 -O{LEDGER_FOLDER_PATH}
```

Example:
```bash
wget  --trust-server-names http://entrypoint3.mainnet-beta.solana.com/snapshot.tar.bz2
```

**Comment by n43o** [comment]
Ahh amazing, I didn't realize I could do that. Thank you so much!
